# Generated by Django 6.0.4 on 2026-04-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortURLModel',
            new_name='ShortURL',
        ),
    ]
